/-
Copyright (c) 2026 Lean FRO LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Author: David Thrane Christiansen
-/
module
public meta import Tests.DocVisibility.Doc
public section

/-!
This test ensures that the document generated by `#doc` is public, so that it can be used from
other modules without the defining module opening a `public section`.
-/

/--
info: Verso.Doc.Part.mk
  #[Verso.Doc.Inline.text "Title"]
  "Title"
  none
  #[Verso.Doc.Block.para #[Verso.Doc.Inline.text "A paragraph.", Verso.Doc.Inline.linebreak "\n"]]
  #[]
-/
#guard_msgs in
#eval %doc Tests.DocVisibility.Doc
