name: Lint GitHub Actions workflows

on: [pull_request, merge_group]

jobs:
    actionlint:
        name: "Lint GitHub Actions workflows"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Run actionlint
              uses: reviewdog/action-actionlint@a8ac3eea598697a830f7d8e701fc9fcbfde88974 # v1.80.0
              with:
                  fail_level: any
                  actionlint_flags: ""
