name: Check Code Formatting

on:
    pull_request:
    merge_group:

jobs:
    check-prettier-formatting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Check formatting with prettier
              uses: creyD/prettier_action@v4.6
              with:
                  dry: true
                  prettier_options: "--check ."
                  prettier_version: 3.7.4

    check-python-formatting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Check Python formatting with ruff
              run: uvx ruff format --check .
