name: Check Code Formatting

on:
    pull_request:
    merge_group:

jobs:
    check-prettier-formatting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Check formatting with prettier
              uses: creyD/prettier_action@8c18391fdc98ed0d884c6345f03975edac71b8f0 # v4.6
              with:
                  dry: true
                  prettier_options: "--check ."
                  prettier_version: 3.7.4

    check-python-formatting:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Install uv
              uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

            - name: Check Python formatting with ruff
              run: uvx ruff format --check .
